// Generated by gencpp from file open_manipulator_msgs/SetKinematicsPoseRequest.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_MSGS_MESSAGE_SETKINEMATICSPOSEREQUEST_H
#define OPEN_MANIPULATOR_MSGS_MESSAGE_SETKINEMATICSPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <open_manipulator_msgs/KinematicsPose.h>

namespace open_manipulator_msgs
{
template <class ContainerAllocator>
struct SetKinematicsPoseRequest_
{
  typedef SetKinematicsPoseRequest_<ContainerAllocator> Type;

  SetKinematicsPoseRequest_()
    : kinematics_pose()  {
    }
  SetKinematicsPoseRequest_(const ContainerAllocator& _alloc)
    : kinematics_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::open_manipulator_msgs::KinematicsPose_<ContainerAllocator>  _kinematics_pose_type;
  _kinematics_pose_type kinematics_pose;





  typedef boost::shared_ptr< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetKinematicsPoseRequest_

typedef ::open_manipulator_msgs::SetKinematicsPoseRequest_<std::allocator<void> > SetKinematicsPoseRequest;

typedef boost::shared_ptr< ::open_manipulator_msgs::SetKinematicsPoseRequest > SetKinematicsPoseRequestPtr;
typedef boost::shared_ptr< ::open_manipulator_msgs::SetKinematicsPoseRequest const> SetKinematicsPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator1> & lhs, const ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.kinematics_pose == rhs.kinematics_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator1> & lhs, const ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace open_manipulator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "061ceb25b20ec55ef37bf7bab518c5c3";
  }

  static const char* value(const ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x061ceb25b20ec55eULL;
  static const uint64_t static_value2 = 0xf37bf7bab518c5c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "open_manipulator_msgs/SetKinematicsPoseRequest";
  }

  static const char* value(const ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "KinematicsPose kinematics_pose\n"
"\n"
"================================================================================\n"
"MSG: open_manipulator_msgs/KinematicsPose\n"
"string    	        group_name\n"
"geometry_msgs/Pose  pose\n"
"float64    max_accelerations_scaling_factor\n"
"float64    max_velocity_scaling_factor\n"
"float64    tolerance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kinematics_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetKinematicsPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::open_manipulator_msgs::SetKinematicsPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "kinematics_pose: ";
    s << std::endl;
    Printer< ::open_manipulator_msgs::KinematicsPose_<ContainerAllocator> >::stream(s, indent + "  ", v.kinematics_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPEN_MANIPULATOR_MSGS_MESSAGE_SETKINEMATICSPOSEREQUEST_H
