// Generated by gencpp from file open_manipulator_msgs/State.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_MSGS_MESSAGE_STATE_H
#define OPEN_MANIPULATOR_MSGS_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace open_manipulator_msgs
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : robot()  {
    }
  State_(const ContainerAllocator& _alloc)
    : robot(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_type;
  _robot_type robot;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(IS_MOVING)
  #undef IS_MOVING
#endif
#if defined(_WIN32) && defined(STOPPED)
  #undef STOPPED
#endif


  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> IS_MOVING;
  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> STOPPED;

  typedef boost::shared_ptr< ::open_manipulator_msgs::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::open_manipulator_msgs::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::open_manipulator_msgs::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::open_manipulator_msgs::State > StatePtr;
typedef boost::shared_ptr< ::open_manipulator_msgs::State const> StateConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      State_<ContainerAllocator>::IS_MOVING =
        
          "\"IS_MOVING\""
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      State_<ContainerAllocator>::STOPPED =
        
          "\"STOPPED\""
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::open_manipulator_msgs::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::open_manipulator_msgs::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::open_manipulator_msgs::State_<ContainerAllocator1> & lhs, const ::open_manipulator_msgs::State_<ContainerAllocator2> & rhs)
{
  return lhs.robot == rhs.robot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::open_manipulator_msgs::State_<ContainerAllocator1> & lhs, const ::open_manipulator_msgs::State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace open_manipulator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::open_manipulator_msgs::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open_manipulator_msgs::State_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_manipulator_msgs::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_manipulator_msgs::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_manipulator_msgs::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_manipulator_msgs::State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::open_manipulator_msgs::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94370aa4b03eef51ce4d539f789d976f";
  }

  static const char* value(const ::open_manipulator_msgs::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94370aa4b03eef51ULL;
  static const uint64_t static_value2 = 0xce4d539f789d976fULL;
};

template<class ContainerAllocator>
struct DataType< ::open_manipulator_msgs::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "open_manipulator_msgs/State";
  }

  static const char* value(const ::open_manipulator_msgs::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::open_manipulator_msgs::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "########################################\n"
"# CONSTANTS\n"
"########################################\n"
"string IS_MOVING = \"IS_MOVING\"\n"
"string STOPPED = \"STOPPED\"\n"
"\n"
"########################################\n"
"# Messages\n"
"########################################\n"
"string robot\n"
;
  }

  static const char* value(const ::open_manipulator_msgs::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::open_manipulator_msgs::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::open_manipulator_msgs::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::open_manipulator_msgs::State_<ContainerAllocator>& v)
  {
    s << indent << "robot: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPEN_MANIPULATOR_MSGS_MESSAGE_STATE_H
