// Generated by gencpp from file crazyflie_driver/NotifySetpointsStop.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_DRIVER_MESSAGE_NOTIFYSETPOINTSSTOP_H
#define CRAZYFLIE_DRIVER_MESSAGE_NOTIFYSETPOINTSSTOP_H

#include <ros/service_traits.h>


#include <crazyflie_driver/NotifySetpointsStopRequest.h>
#include <crazyflie_driver/NotifySetpointsStopResponse.h>


namespace crazyflie_driver
{

struct NotifySetpointsStop
{

typedef NotifySetpointsStopRequest Request;
typedef NotifySetpointsStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NotifySetpointsStop
} // namespace crazyflie_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie_driver::NotifySetpointsStop > {
  static const char* value()
  {
    return "5e1e40fcf516d3883bc228627d3e1e43";
  }

  static const char* value(const ::crazyflie_driver::NotifySetpointsStop&) { return value(); }
};

template<>
struct DataType< ::crazyflie_driver::NotifySetpointsStop > {
  static const char* value()
  {
    return "crazyflie_driver/NotifySetpointsStop";
  }

  static const char* value(const ::crazyflie_driver::NotifySetpointsStop&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie_driver::NotifySetpointsStopRequest> should match
// service_traits::MD5Sum< ::crazyflie_driver::NotifySetpointsStop >
template<>
struct MD5Sum< ::crazyflie_driver::NotifySetpointsStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::NotifySetpointsStop >::value();
  }
  static const char* value(const ::crazyflie_driver::NotifySetpointsStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::NotifySetpointsStopRequest> should match
// service_traits::DataType< ::crazyflie_driver::NotifySetpointsStop >
template<>
struct DataType< ::crazyflie_driver::NotifySetpointsStopRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::NotifySetpointsStop >::value();
  }
  static const char* value(const ::crazyflie_driver::NotifySetpointsStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie_driver::NotifySetpointsStopResponse> should match
// service_traits::MD5Sum< ::crazyflie_driver::NotifySetpointsStop >
template<>
struct MD5Sum< ::crazyflie_driver::NotifySetpointsStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::NotifySetpointsStop >::value();
  }
  static const char* value(const ::crazyflie_driver::NotifySetpointsStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::NotifySetpointsStopResponse> should match
// service_traits::DataType< ::crazyflie_driver::NotifySetpointsStop >
template<>
struct DataType< ::crazyflie_driver::NotifySetpointsStopResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::NotifySetpointsStop >::value();
  }
  static const char* value(const ::crazyflie_driver::NotifySetpointsStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_DRIVER_MESSAGE_NOTIFYSETPOINTSSTOP_H
