// Generated by gencpp from file two_link/paramResponse.msg
// DO NOT EDIT!


#ifndef TWO_LINK_MESSAGE_PARAMRESPONSE_H
#define TWO_LINK_MESSAGE_PARAMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace two_link
{
template <class ContainerAllocator>
struct paramResponse_
{
  typedef paramResponse_<ContainerAllocator> Type;

  paramResponse_()
    {
    }
  paramResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::two_link::paramResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::two_link::paramResponse_<ContainerAllocator> const> ConstPtr;

}; // struct paramResponse_

typedef ::two_link::paramResponse_<std::allocator<void> > paramResponse;

typedef boost::shared_ptr< ::two_link::paramResponse > paramResponsePtr;
typedef boost::shared_ptr< ::two_link::paramResponse const> paramResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::two_link::paramResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::two_link::paramResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace two_link

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::two_link::paramResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::two_link::paramResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::two_link::paramResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::two_link::paramResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::two_link::paramResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::two_link::paramResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::two_link::paramResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::two_link::paramResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::two_link::paramResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "two_link/paramResponse";
  }

  static const char* value(const ::two_link::paramResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::two_link::paramResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::two_link::paramResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::two_link::paramResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct paramResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::two_link::paramResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::two_link::paramResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TWO_LINK_MESSAGE_PARAMRESPONSE_H
